### ISSUE TITLE
Data showing up in wrong row

### ISSUE THREAD

**Issue by guido4000** [nebev/ssg-js#5]
The description, tags and address of the first entry show up in the second row. And it is the same for all following rows.

![1 ssh server selection gui s node 2016-01-16 16-23-12](https://cloud.githubusercontent.com/assets/505155/12371672/88b7b6f2-bc6d-11e5-8c37-74d96a4192d2.png)

**Comment by hbokh** [comment]
Dito

**Comment by nebev** [comment]
This one is hard to troubleshoot without seeing the underlying config.
Is it possible to paste an anonymised version that causes this issue?

**Comment by hbokh** [comment]
Sure, fair enough. Here's the top of mine:

```
Host *
  ControlMaster auto
  ControlPath /tmp/ssh_mux_%h_%p_%r
  ServerAliveInterval 60
  UseRoaming no

Host vagrant
  Hostname 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/charlie/.vagrant.d/insecure_private_key
  IdentitiesOnly yes

Host rumpelstiltskin
  # @description My BSD server
  # @tags bsd home
  Hostname 192.168.10.1
  User charlie

Host dd-wrt
  Hostname 192.168.20.254
  User bravo

#Host raspberrypi
Host rpi
  # @description Raspberry Pi
  # @tags rpi home
  User alpha

```

Even though only part of it, the behaviour / issue is the same (in iTerm2, OSX).

**Comment by hbokh** [comment]
I think I found the issue on my side. When I put the description and tags in front of `Host` it's OK:

```
# @description My BSD server
# @tags bsd home
Host rumpelstiltskin
  Hostname 192.168.10.1
  User charlie
```

PEBKAC.

**Comment by nebev** [comment]
Haha. Yep.
The @ lines must go before the host. Much like a DocBlock.
Assuming @guido4000  is having the same issue, so going to close.

**Comment by guido4000** [comment]
Perfect. Problem solved. Thank you.
